import Head from 'next/head'
import styles from './Home.module.css'
import PageLayout from '@/components/layouts/PageLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <main className={styles.main}>
          <h1>Home Page</h1>
        </main>
      </PageLayout>
    </>
  )
}
